//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.03 at 05:55:41 PM AST 
//


package by.test.webservices.recordservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.test.webservices.recordservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.test.webservices.recordservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetNumberOfRecordsResponse }
     * 
     */
    public GetNumberOfRecordsResponse createGetNumberOfRecordsResponse() {
        return new GetNumberOfRecordsResponse();
    }

    /**
     * Create an instance of {@link GetNumberOfRecordsRequest }
     * 
     */
    public GetNumberOfRecordsRequest createGetNumberOfRecordsRequest() {
        return new GetNumberOfRecordsRequest();
    }

    /**
     * Create an instance of {@link SearchRecordsResponse }
     * 
     */
    public SearchRecordsResponse createSearchRecordsResponse() {
        return new SearchRecordsResponse();
    }

    /**
     * Create an instance of {@link AddRecordToVocabloryRequest }
     * 
     */
    public AddRecordToVocabloryRequest createAddRecordToVocabloryRequest() {
        return new AddRecordToVocabloryRequest();
    }

    /**
     * Create an instance of {@link GetAllVocabloriesResponse }
     * 
     */
    public GetAllVocabloriesResponse createGetAllVocabloriesResponse() {
        return new GetAllVocabloriesResponse();
    }

    /**
     * Create an instance of {@link SearchRecordsRequest }
     * 
     */
    public SearchRecordsRequest createSearchRecordsRequest() {
        return new SearchRecordsRequest();
    }

    /**
     * Create an instance of {@link AddRecordToVocabloryResponse }
     * 
     */
    public AddRecordToVocabloryResponse createAddRecordToVocabloryResponse() {
        return new AddRecordToVocabloryResponse();
    }

    /**
     * Create an instance of {@link GetAllVocabloriesRequest }
     * 
     */
    public GetAllVocabloriesRequest createGetAllVocabloriesRequest() {
        return new GetAllVocabloriesRequest();
    }

}
